extend type Order {
  """
  ✨ List `OrderItem` objects in a one-to-many relationship (where `OrderItem`.`order` is this object).
  """
  orderItems_on_order(
    """
    Filter condition to narrow down the query results.
    """
    where: OrderItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [OrderItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: OrderItem_Having
  ): [OrderItem!]! @fdc_generated(from: "OrderItem.order", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Order", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Order` table.
  """
  _count: Int! @fdc_generated(from: "Order.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `customerEmail` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  customerEmail_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.customerEmail", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `customerName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  customerName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.customerName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `discountAmount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  discountAmount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.discountAmount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `orderDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  orderDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.orderDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `paymentMethod` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  paymentMethod_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.paymentMethod", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `processedById` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  processedById_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.processedById", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `totalAmount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  totalAmount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.totalAmount", purpose: QUERY_COUNT)
  """
  ✨ Sum the `discountAmount` field in the `Order` table.
  """
  discountAmount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Order.discountAmount", purpose: QUERY_SUM)
  """
  ✨ Sum the `totalAmount` field in the `Order` table.
  """
  totalAmount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Order.totalAmount", purpose: QUERY_SUM)
  """
  ✨ Average the `discountAmount` field in the `Order` table.
  """
  discountAmount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Order.discountAmount", purpose: QUERY_AVG)
  """
  ✨ Average the `totalAmount` field in the `Order` table.
  """
  totalAmount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Order.totalAmount", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Order` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Order.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `discountAmount` field in the `Order` table.
  """
  discountAmount_min: Float @fdc_generated(from: "Order.discountAmount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `orderDate` field in the `Order` table.
  """
  orderDate_min: Timestamp @fdc_generated(from: "Order.orderDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `totalAmount` field in the `Order` table.
  """
  totalAmount_min: Float @fdc_generated(from: "Order.totalAmount", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Order` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Order.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `discountAmount` field in the `Order` table.
  """
  discountAmount_max: Float @fdc_generated(from: "Order.discountAmount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `orderDate` field in the `Order` table.
  """
  orderDate_max: Timestamp @fdc_generated(from: "Order.orderDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `totalAmount` field in the `Order` table.
  """
  totalAmount_max: Float @fdc_generated(from: "Order.totalAmount", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Order.id", purpose: GLOBAL_ID)
}
extend type OrderItem {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "OrderItem", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `OrderItem` table.
  """
  _count: Int! @fdc_generated(from: "OrderItem.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OrderItem` table where the `discountApplied` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  discountApplied_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OrderItem.discountApplied", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OrderItem` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OrderItem.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OrderItem` table where the `orderId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  orderId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OrderItem.orderId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OrderItem` table where the `productId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OrderItem.productId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OrderItem` table where the `quantity` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  quantity_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OrderItem.quantity", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OrderItem` table where the `subtotal` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subtotal_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OrderItem.subtotal", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `OrderItem` table where the `unitPrice` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  unitPrice_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "OrderItem.unitPrice", purpose: QUERY_COUNT)
  """
  ✨ Sum the `discountApplied` field in the `OrderItem` table.
  """
  discountApplied_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OrderItem.discountApplied", purpose: QUERY_SUM)
  """
  ✨ Sum the `quantity` field in the `OrderItem` table.
  """
  quantity_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "OrderItem.quantity", purpose: QUERY_SUM)
  """
  ✨ Sum the `subtotal` field in the `OrderItem` table.
  """
  subtotal_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OrderItem.subtotal", purpose: QUERY_SUM)
  """
  ✨ Sum the `unitPrice` field in the `OrderItem` table.
  """
  unitPrice_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OrderItem.unitPrice", purpose: QUERY_SUM)
  """
  ✨ Average the `discountApplied` field in the `OrderItem` table.
  """
  discountApplied_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OrderItem.discountApplied", purpose: QUERY_AVG)
  """
  ✨ Average the `quantity` field in the `OrderItem` table.
  """
  quantity_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OrderItem.quantity", purpose: QUERY_AVG)
  """
  ✨ Average the `subtotal` field in the `OrderItem` table.
  """
  subtotal_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OrderItem.subtotal", purpose: QUERY_AVG)
  """
  ✨ Average the `unitPrice` field in the `OrderItem` table.
  """
  unitPrice_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "OrderItem.unitPrice", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `discountApplied` field in the `OrderItem` table.
  """
  discountApplied_min: Float @fdc_generated(from: "OrderItem.discountApplied", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `quantity` field in the `OrderItem` table.
  """
  quantity_min: Int @fdc_generated(from: "OrderItem.quantity", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `subtotal` field in the `OrderItem` table.
  """
  subtotal_min: Float @fdc_generated(from: "OrderItem.subtotal", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `unitPrice` field in the `OrderItem` table.
  """
  unitPrice_min: Float @fdc_generated(from: "OrderItem.unitPrice", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `discountApplied` field in the `OrderItem` table.
  """
  discountApplied_max: Float @fdc_generated(from: "OrderItem.discountApplied", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `quantity` field in the `OrderItem` table.
  """
  quantity_max: Int @fdc_generated(from: "OrderItem.quantity", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `subtotal` field in the `OrderItem` table.
  """
  subtotal_max: Float @fdc_generated(from: "OrderItem.subtotal", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `unitPrice` field in the `OrderItem` table.
  """
  unitPrice_max: Float @fdc_generated(from: "OrderItem.unitPrice", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "OrderItem.id", purpose: GLOBAL_ID)
}
extend type Product {
  """
  ✨ List `OrderItem` objects in a one-to-many relationship (where `OrderItem`.`product` is this object).
  """
  orderItems_on_product(
    """
    Filter condition to narrow down the query results.
    """
    where: OrderItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [OrderItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: OrderItem_Having
  ): [OrderItem!]! @fdc_generated(from: "OrderItem.product", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Product", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Product` table.
  """
  _count: Int! @fdc_generated(from: "Product.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `barcode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  barcode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.barcode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `category` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  category_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.category", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `price` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  price_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.price", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `stockQuantity` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  stockQuantity_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.stockQuantity", purpose: QUERY_COUNT)
  """
  ✨ Sum the `price` field in the `Product` table.
  """
  price_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.price", purpose: QUERY_SUM)
  """
  ✨ Sum the `stockQuantity` field in the `Product` table.
  """
  stockQuantity_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Product.stockQuantity", purpose: QUERY_SUM)
  """
  ✨ Average the `price` field in the `Product` table.
  """
  price_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.price", purpose: QUERY_AVG)
  """
  ✨ Average the `stockQuantity` field in the `Product` table.
  """
  stockQuantity_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.stockQuantity", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Product` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Product.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `price` field in the `Product` table.
  """
  price_min: Float @fdc_generated(from: "Product.price", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `stockQuantity` field in the `Product` table.
  """
  stockQuantity_min: Int @fdc_generated(from: "Product.stockQuantity", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Product` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Product.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `price` field in the `Product` table.
  """
  price_max: Float @fdc_generated(from: "Product.price", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `stockQuantity` field in the `Product` table.
  """
  stockQuantity_max: Int @fdc_generated(from: "Product.stockQuantity", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Product.id", purpose: GLOBAL_ID)
}
extend type Shift {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Shift", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Shift` table.
  """
  _count: Int! @fdc_generated(from: "Shift.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shift` table where the `employeeId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  employeeId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shift.employeeId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shift` table where the `endCash` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endCash_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shift.endCash", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shift` table where the `endTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shift.endTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shift` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shift.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shift` table where the `salesTotal` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  salesTotal_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shift.salesTotal", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shift` table where the `startCash` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startCash_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shift.startCash", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Shift` table where the `startTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Shift.startTime", purpose: QUERY_COUNT)
  """
  ✨ Sum the `endCash` field in the `Shift` table.
  """
  endCash_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Shift.endCash", purpose: QUERY_SUM)
  """
  ✨ Sum the `salesTotal` field in the `Shift` table.
  """
  salesTotal_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Shift.salesTotal", purpose: QUERY_SUM)
  """
  ✨ Sum the `startCash` field in the `Shift` table.
  """
  startCash_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Shift.startCash", purpose: QUERY_SUM)
  """
  ✨ Average the `endCash` field in the `Shift` table.
  """
  endCash_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Shift.endCash", purpose: QUERY_AVG)
  """
  ✨ Average the `salesTotal` field in the `Shift` table.
  """
  salesTotal_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Shift.salesTotal", purpose: QUERY_AVG)
  """
  ✨ Average the `startCash` field in the `Shift` table.
  """
  startCash_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Shift.startCash", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `endCash` field in the `Shift` table.
  """
  endCash_min: Float @fdc_generated(from: "Shift.endCash", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `endTime` field in the `Shift` table.
  """
  endTime_min: Timestamp @fdc_generated(from: "Shift.endTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `salesTotal` field in the `Shift` table.
  """
  salesTotal_min: Float @fdc_generated(from: "Shift.salesTotal", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startCash` field in the `Shift` table.
  """
  startCash_min: Float @fdc_generated(from: "Shift.startCash", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startTime` field in the `Shift` table.
  """
  startTime_min: Timestamp @fdc_generated(from: "Shift.startTime", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `endCash` field in the `Shift` table.
  """
  endCash_max: Float @fdc_generated(from: "Shift.endCash", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `endTime` field in the `Shift` table.
  """
  endTime_max: Timestamp @fdc_generated(from: "Shift.endTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `salesTotal` field in the `Shift` table.
  """
  salesTotal_max: Float @fdc_generated(from: "Shift.salesTotal", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startCash` field in the `Shift` table.
  """
  startCash_max: Float @fdc_generated(from: "Shift.startCash", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startTime` field in the `Shift` table.
  """
  startTime_max: Timestamp @fdc_generated(from: "Shift.startTime", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Shift.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `Order` objects in a one-to-many relationship (where `Order`.`processedBy` is this object).
  """
  orders_on_processedBy(
    """
    Filter condition to narrow down the query results.
    """
    where: Order_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Order_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Order_Having
  ): [Order!]! @fdc_generated(from: "Order.processedBy", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Shift` objects in a one-to-many relationship (where `Shift`.`employee` is this object).
  """
  shifts_on_employee(
    """
    Filter condition to narrow down the query results.
    """
    where: Shift_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Shift_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Shift_Having
  ): [Shift!]! @fdc_generated(from: "Shift.employee", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `passwordHash` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  passwordHash_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.passwordHash", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.role", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.username", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
